In [2]:
import numpy as np

In [3]:
arr = np.zeros((5,2))

In [4]:
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
arr[3,1]= 5

In [6]:
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 5.],
       [0., 0.]])

In [7]:
arr_ones = np.ones((5,4))

In [8]:
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
a = np.arange(10)

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr_ones.shape

(5, 4)

In [12]:
a.shape

(10,)

In [13]:
a[5]

5

In [14]:
a = np.arange(10).reshape(2,5)

In [15]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
a = np.arange(10)

In [18]:
a.shape=(5,2)

In [19]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [21]:
np.linspace(1,5,6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [22]:
a 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
a = np.arange(10).reshape(1,10)

In [24]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
a[:5]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
a[0,5]

5

In [27]:
a[0,-5]

5

In [28]:
a[0,-10]

0

In [29]:
a = np.arange(35).reshape(7,5)

In [30]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [31]:
a>18

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [32]:
a[a>18]

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [33]:
a = np.ones((2,2))

In [34]:
a

array([[1., 1.],
       [1., 1.]])

In [35]:
b = np.ones((2,2))

In [36]:
b

array([[1., 1.],
       [1., 1.]])

In [37]:
b[0,1]=3

In [38]:
b[1,0] = 4

In [39]:
b

array([[1., 3.],
       [4., 1.]])

In [40]:
a

array([[1., 1.],
       [1., 1.]])

In [41]:
a +b

array([[2., 4.],
       [5., 2.]])

In [42]:
a - b

array([[ 0., -2.],
       [-3.,  0.]])

In [43]:
a*b

array([[1., 3.],
       [4., 1.]])

In [44]:
a.dot(b)

array([[5., 4.],
       [5., 4.]])

In [45]:
np.dot(a,b)

array([[5., 4.],
       [5., 4.]])

In [46]:
a@b

array([[5., 4.],
       [5., 4.]])

In [47]:
a

array([[1., 1.],
       [1., 1.]])

In [48]:
b

array([[1., 3.],
       [4., 1.]])

In [49]:
b.sum(axis=0)

array([5., 4.])

In [50]:
b.sum(axis=1)

array([4., 5.])

In [51]:
a = np.random.random((3,4))

In [52]:
a

array([[0.82113842, 0.82794696, 0.51357683, 0.44606627],
       [0.62206745, 0.4875534 , 0.91807937, 0.52982554],
       [0.73842004, 0.31981489, 0.25041283, 0.31536947]])

In [53]:
a = np.floor(10*np.random.random((3,4)))

In [54]:
a

array([[5., 5., 7., 6.],
       [4., 1., 5., 2.],
       [7., 6., 6., 2.]])

In [55]:
a.ravel()

array([5., 5., 7., 6., 4., 1., 5., 2., 7., 6., 6., 2.])

In [56]:
b = a.ravel()

In [57]:
b

array([5., 5., 7., 6., 4., 1., 5., 2., 7., 6., 6., 2.])

In [58]:
a[2,2] = 20

In [59]:
a

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20.,  2.]])

In [60]:
b

array([ 5.,  5.,  7.,  6.,  4.,  1.,  5.,  2.,  7.,  6., 20.,  2.])

In [61]:
c = a

In [62]:
c

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20.,  2.]])

In [63]:
c[2,3]=40

In [64]:
a

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20., 40.]])

In [65]:
d = a.copy()

In [66]:
d

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20., 40.]])

In [67]:
d[1,3]=90

In [68]:
d

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5., 90.],
       [ 7.,  6., 20., 40.]])

In [69]:
a

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20., 40.]])

In [70]:
e = a.flatten()

In [71]:
e

array([ 5.,  5.,  7.,  6.,  4.,  1.,  5.,  2.,  7.,  6., 20., 40.])

In [72]:
a

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20., 40.]])

In [73]:
e[0]=90

In [74]:
e

array([90.,  5.,  7.,  6.,  4.,  1.,  5.,  2.,  7.,  6., 20., 40.])

In [75]:
a

array([[ 5.,  5.,  7.,  6.],
       [ 4.,  1.,  5.,  2.],
       [ 7.,  6., 20., 40.]])

In [76]:
a.T

array([[ 5.,  4.,  7.],
       [ 5.,  1.,  6.],
       [ 7.,  5., 20.],
       [ 6.,  2., 40.]])